version: '3.8'
services:
  fastify-app:
    container_name: fastify-app
    #build: .
    image: thanhdat1047/server:v2
    volumes:
      - .:/src
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    env_file: .env
    networks:
      - app-networks
  postgres:
    image: postgres:15
    restart: always
    ports:
      - "5433:5432"
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-networks
networks:
  app-networks:
    driver: bridge

volumes:
  postgres_data:
